### ISSUE TITLE
phyiscal activity tab

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#1]
@usr110 
category names are wrong
should be clear if these are midpoints are top of ranges.
top category 52.7+ vs  2nd top category 52.8

also under scenario with more activity  (Cm 64, equity 1, ebike 1) there are fewer people in the top 52.7+ category (comparing baseline vs scenario)- in fact looks like an omission as there are zero people in the top category under the scenario

**Comment by usr110** [comment]
Has been fixed
