### ISSUE TITLE
comparing between regions

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#15]
It would be nice to have  a way to compare the regions e.g. high level comparison North West vs England or North West vs North East, and within this to compare subpopulations e.g. older people in NW vs older people in NE

**Comment by TSzDefr** [comment]
1. Mode Share - **ready**
2. Journey Time - **not applicable**
3. Miles Cycled - **ready**
4. Physical Activity - **ready**
5. Health - **ready**
6. Car Miles - **ready**
7. CO2 - **ready**
