### ISSUE TITLE
co2 wrong for regions

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#30]
@TSzDefr @audev 
[Doc2.docx](https://github.com/ITHIM/ICT/files/595027/Doc2.docx)
the co2 emissions seem to go up with more cycling

**Comment by audev** [comment]
@JDWoodcock  Can you give an example of what's wrong with the regions? Thanks

**Comment by audev** [comment]
@JDWoodcock  Still unclear about the wrong CO2 at region level.

**Comment by JDWoodcock** [comment]
compare the patterns to north east to patterns for england as a a whole @audev

**Comment by audev** [comment]
Closing as nos. looking right in <ICT_aggr_reg_v2.rds>.

Fixed here: 
https://github.com/ITHIM/ICT-Model/commit/df1790dd5ab37183310860e2f7043d78707310d8
https://github.com/ITHIM/ICT-Model/commit/5ff4c159155f0bba7dcfc6423d0d7aca85b295f1
