### ISSUE TITLE
No trips data being wrongly added in aggregates

### ISSUE THREAD

**Issue by audev** [ITHIM/ICT#37]
E.g in lines
https://github.com/ITHIM/ICT-Model/blob/master/3_CBM2_Aggregates-2012.R#L123

and 

https://github.com/ITHIM/ICT-Model/blob/master/3_CBM2_Aggregates-2012.R#L127

**Comment by usr110** [comment]
@audev Thanks for fixing the issue.
Can you please also mention the commit where the issue was fixed? It's easier to track then.

**Comment by audev** [comment]
Fixed here: 
https://github.com/ITHIM/ICT-Model/commit/1064bc8747c369ea519a6c61f82500b6354aa34f

**Comment by usr110** [comment]
Great, thanks.
