### ISSUE TITLE
Subtitles for tabs

### ISSUE THREAD

**Issue by usr110** [ITHIM/ICT#38]
For a region, once an `alternate region` is selected, it's title should be represented in `Scenario (Total Population)`. Also the order of the bars should be:

1. Selected region
2. Alternate region

opposite of what it is at the moment.

**Comment by TSzDefr** [comment]
Subtitles were also adjusted to reflect change of the order of columns.
![image](https://cloud.githubusercontent.com/assets/19797488/21320969/29a186c4-c613-11e6-9687-fe3d1fb36505.png)
