### ISSUE TITLE
adding the missing tabs

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#5]
the tabs available for version 1 need to be added to version 2

```
Mode Share- done
Journey Time- to be added
Miles Cycled- to be added
Physical Activity- done
Health- done
Car Miles- to be added
CO2-done
Summary-done
About-done
```

**Comment by TSzDefr** [comment]
All tabs are available now. Please verify figures/charts

**Comment by usr110** [comment]
Having some permission issues with the server @TSzDefr Hopefully by tomorrow I will update it, so that everyone can have a look at it.

**Comment by usr110** [comment]
Have pushed the current repo on the test server. You can see it here:

http://npct0.vs.mythic-beasts.com/ict-regional/

Also added a field which shows the baseline cycling percentage

With 133mb of trip data, it takes a while to load the application. Also takes a while to switch to another region. Need to improve it.

Flagging it up for @JDWoodcock @TSzDefr and @AnnaGoodman1

**Comment by usr110** [comment]
Temporarily removed the `journey time` tab

**Comment by usr110** [comment]
Re-added the `journey time` tab. Thanks to @TSzDefr for all the work. 

https://github.com/ITHIM/ICT/pull/22
