### ISSUE TITLE
direct probability method

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#6]
confirming if the two different ways of calculating the direct probabilty give the same result

**Comment by TSzDefr** [comment]
Should be verified. Files which compare results of DP approaches are here: [calcCyclistsDPDiffAppro_England_output.csv](https://github.com/ITHIM/ICT-Model/blob/5c8bca8269b9d48bf89bb689fe0b8a771e7ec36f/tests/calcCyclistsDPDiffAppro_England_output.csv) and [calcCyclistsDPDiffAppro_output.csv](https://github.com/ITHIM/ICT-Model/blob/5c8bca8269b9d48bf89bb689fe0b8a771e7ec36f/tests/calcCyclistsDPDiffAppro_output.csv)
