### ISSUE TITLE
PA tab

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#64]
within the tab this should have heading to indicate this is leisure time PA

**Comment by TSzDefr** [comment]
So after the change both titles should be _Sub/Total-Population [England] - Marginal MET Hours **(leisure time)**_?

**Comment by AnnaGoodman1** [comment]
@JDWoodcock , I don't think 'leisure time' is quite right if also include walking and cycling for transport? would 'Marginal MET hours (walking, cycling, sports and recreation activity)' work (and fit?!)

**Comment by TSzDefr** [comment]
Change in the last PR - it will be available on the test server after merge.
