### ISSUE TITLE
pa tab title

### ISSUE THREAD

**Issue by AnnaGoodman1** [ITHIM/ICT#68]
There is currently a mistake on thePA tab for the percent meeting guidelines – the title is not correct. Instead of saying 'Marginal MET hours' it should say '% meeting activity guidelines'

![image](https://cloud.githubusercontent.com/assets/11818225/24354906/a5f2af76-12eb-11e7-9dbc-819e8e4963d2.png)

**Comment by TSzDefr** [comment]
Change in the last PR - it will be available on the test server after merge. I also modified xAxis title to reflect change in the title - I hope this is ok.
![image](https://cloud.githubusercontent.com/assets/19797488/24367027/6a26c9ca-131b-11e7-84b4-780f53005376.png)

**Comment by usr110** [comment]
Great work, tomek!
Closed in https://github.com/ITHIM/ICT/commit/44c73beccc58ffe70a1cdc72a68c264c33f2094f
