### ISSUE TITLE
5% of population cyclists

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#7]
this scenario is giving some odd results.
 In particular equity does not improve the values (e.g. mode share cycling) for older women. Please check and see why this is happening

**Comment by TSzDefr** [comment]
Should be verified if this issue still exists in the regenerated data

**Comment by usr110** [comment]
With equity on there's an increase of `0.1` % (from `0.8` to `0.9`) with the following configurations:

![ict-lowest-scenario-equity](https://cloud.githubusercontent.com/assets/10958628/18551858/2d82d970-7b52-11e6-9373-2d22c6bc499d.png)
