### ISSUE TITLE
phy act tab

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#72]
histogram of PA dist when downloading graph the x axis comes out a bit ugly
![image](https://cloud.githubusercontent.com/assets/11028720/25041926/b2d880e8-210b-11e7-8538-2f54177e5adf.png)

**Comment by usr110** [comment]
Fixed in https://github.com/ITHIM/ICT/commit/9e30791540743d5609bde1030a3a50e2a93fb0a2
