### ISSUE TITLE
subpopulation

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#75]
even when the whole population is selected the graph legend says subpopulation and this is confusing, while the title says total popualtion.  I wonder if it is ever needed to say subpop and total pop?
![image](https://cloud.githubusercontent.com/assets/11028720/25044218/587b091a-211d-11e7-9144-1875015dab89.png)

**Comment by usr110** [comment]
Fixed in https://github.com/ITHIM/ICT/commit/e7b4d391870c997aae3862e83de7239b5e7855e8
