### ISSUE TITLE
if region is already above a given % cyclists & showing baseline

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ICT#8]
We need to see % cyclists at baseline for England and each region

When a region has > 5% cyclists at baseline e.g. east of england then for scenario of 5% (and 10% if appropriate) we should have those lower options greyed out

**Comment by TSzDefr** [comment]
It is ready - when a region has > % cyclists at baseline these values are removed from the dropdown with DP

**Comment by JDWoodcock** [comment]
thanks, can we also see on the front page what the baseline % is for that area? Currently one has to go to summary tab to see this.

**Comment by usr110** [comment]
@JDWoodcock See this comment: https://github.com/ITHIM/ICT/issues/5#issuecomment-245909636
